# Tổng quan & Metrics đánh giá

Mục tiêu: Xây dựng mô hình dự đoán điểm thi của học sinh dựa trên yếu tố đầu vào
+ số giờ học
+ Thói quen học tập
+ chất lượng giấc ngủ ,....

## 1.1 Xác định bài toán

Bài toán Regression_1 dạng bài toán Supervised Learning trong Machine Learning
    <br>*Regression:* bài toán dự đoán 1 giá trị liên tục hay vì phân loại thành các nhóm rời rạc
    <br>VD: Thay vì dự đoán 1 học sinh "Đỗ hay trượt"(Classification), mô hình Regression có thể trả về con số cụ thể về điểm thi như 75.5 or 82.3 - tương tự dự đoán giá nhà hay nhiệt độ
    <br>*Biến mục tiêu:* **exam_score**

## 1.2 Metrics đánh giá

Bài toán Classification: dùng Accuaracy làm thước đo 
<br> Bài toán *Regression*, hiệu suất mô hình đánh giá thông qua **RMSE**, **MAE**, **R^2 Score**
<br> 1.**RMSE** (Root Mean Squared Error)- sai số bình phương trung bình đo lường sai số trung bình giữa giá trị dự đoán và thực tế
<br>    + Giá trị càng thấp càng tốt
<br>    + RMSE nhạy cảm với outliers

# 2. Thu thập dữ liệu

Sử dụng Kaggle

# 3 EDA

## 3.1 Load và Khảo sát dữ liệu ban đầu

In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('D:/Machine Learning/Grade of student/notebook and dataset/train.csv')
df.head()

,id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,0,21,female,b.sc,7.91,98.8,no,4.9,average,online videos,low,easy,78.3
1,1,18,other,diploma,4.95,94.8,yes,4.7,poor,self-study,medium,moderate,46.7
2,2,20,female,b.sc,4.68,92.6,yes,5.8,poor,coaching,high,moderate,99.0
3,3,19,male,b.sc,2.00,49.5,yes,8.3,average,group study,high,moderate,63.9
4,4,23,male,bca,7.65,86.9,yes,9.6,good,self-study,high,easy,100.0

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 630000 entries, 0 to 629999
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                630000 non-null  int64
 1   age               630000 non-null  int64
 2   gender            630000 non-null  str
 3   course            630000 non-null  str
 4   study_hours       630000 non-null  float64
 5   class_attendance  630000 non-null  float64
 6   internet_access   630000 non-null  str
 7   sleep_hours       630000 non-null  float64
 8   sleep_quality     630000 non-null  str
 9   study_method      630000 non-null  str
 10  facility_rating   630000 non-null  str
 11  exam_difficulty   630000 non-null  str
 12  exam_score        630000 non-null  float64
dtypes: float64(4), int64(2), str(7)
memory usage: 62.5 MB

Nhận xét: Dữ liệu gồm 630000 bản ghi vs 13 cột, đều non-null
<br> tập  dữ liệu lý tưởng

In [7]:
df.describe()

,id,age,study_hours,class_attendance,sleep_hours,exam_score
count,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000
mean,314999.500000,20.545821,4.002337,71.987261,7.072758,62.506672
std,181865.479132,2.260238,2.359880,17.430098,1.744811,18.916884
min,0.000000,17.000000,0.080000,40.600000,4.100000,19.599000
25%,157499.750000,19.000000,1.970000,57.000000,5.600000,48.800000
50%,314999.500000,21.000000,4.000000,72.600000,7.100000,62.600000
75%,472499.250000,23.000000,6.050000,87.200000,8.600000,76.300000
max,629999.000000,24.000000,7.910000,99.400000,9.900000,100.000000

Nhan xet
<br> Quy mo lon
<br> Phan phoi diem thi rong
<br>  thoi gian hoc trung binh

## 3.2 Kiem tra su lieu

### 3.2.1 Missing values

In [8]:
df.isnull().sum()

id                  0
age                 0
gender              0
course              0
study_hours         0
class_attendance    0
internet_access     0
sleep_hours         0
sleep_quality       0
study_method        0
facility_rating     0
exam_difficulty     0
exam_score          0
dtype: int64

### 3.2.2 Duplicate records

In [9]:
df.shape

(630000, 13)

In [10]:
df.duplicated().sum()

np.int64(0)

### 3.2.3 Outliers (Kiểm tra biến ngoại lai)

In [ ]:
for col in numeric_cols: